services:
  kafka-1:
    image: bitnami/kafka:3.5.2
    ports:
      - "${KAFKA_1_INTERNAL_PORT}:9092"
      - "${KAFKA_1_EXTERNAL_PORT}:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092,EXTERNAL://${KAFKA_1_EXTERNAL_HOST}:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-1:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  kafka-ui-1:
    image: provectuslabs/kafka-ui:latest
    ports:  
      - "${KAFKA_UI_1_PORT}:8080"
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
    depends_on:
      - kafka-1

  mongo-1:
    image: mongo:4.4.26
    ports:
      - "${MONGO_1_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_1_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_1_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_1_DATABASE}

  elasticsearch-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    ports:
      - "${ELASTICSEARCH_1_EXTERNAL_PORT}:9200"
      - "${ELASTICSEARCH_1_INTERNAL_PORT}:9300"
    environment:
      - discovery.type=single-node
      - http.cors.allow-origin="*"
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - xpack.security.enabled=false
      - ELASTIC_USERNAME=${ELASTICSEARCH_1_USERNAME}
      - ELASTIC_PASSWORD=${ELASTICSEARCH_1_PASSWORD}
  
  dejavu-1:
    image: appbaseio/dejavu:3.6.0
    ports:
      - "${DEJAVU_1_PORT}:1358"
    depends_on:
      - elasticsearch-1
